# Generated by Django 4.2.6 on 2023-10-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_artist_first_name_artist_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
